# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  displayName: Console app build
  inputs:
    command: 'build'
    projects: 'ConsoleAppTestBuild/ConsoleAppTestBuild/ConsoleAppTestBuild.csproj'
    arguments: 
    
- task: DotNetCoreCLI@2
  displayName: Web api app build
  inputs:
    command: 'build'
    projects: 'BasicWebapiUnitTest/BasicWebapiUnitTest/BasicWebapiUnitTest.csproj'

- task: DotNetCoreCLI@2
  displayName: Web api unit test build
  inputs:
    command: 'test'
    projects: 'BasicWebapiUnitTest/TestProjectBasicApi/TestProjectBasicApi.csproj'